{% set name = "constyle" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2607748c787ef4f033715b0cf2474457427bf81ce7b8d21faf68dd62267c9d14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - importlib-metadata >=4.11.0,<5.0.0a

test:
  imports:
    - constyle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/abrahammurciano/python-constyle
  summary: A Python library to add style to your console
  description: |
    A Python library to add style to your console.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://abrahammurciano.github.io/python-constyle/constyle
  dev_url: https://github.com/abrahammurciano/python-constyle

extra:
  recipe-maintainers:
    - abrahammurciano
