{% set name = "constyle" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99b975a256ca469e545bee869185bd1d477b88022ddcec6e059c7a74d22ef59e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - constyle = constyle.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - importlib-metadata >=4.11.0,<5.0.0a
    - attributes-doc >=0.3.0

test:
  imports:
    - constyle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/abrahammurciano/python-constyle
  summary: A Python library to add style to your console
  description: |
    A Python library to add style to your console.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://abrahammurciano.github.io/python-constyle/constyle
  dev_url: https://github.com/abrahammurciano/python-constyle

extra:
  recipe-maintainers:
    - abrahammurciano
