{% set name = "constyle" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38e420c90aeb9b316d964adf249eb27be80ed0671934b1954ec9b86d12a93d3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - constyle = constyle.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - importlib-metadata >=4.11.0,<5.0.0a

test:
  imports:
    - constyle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/abrahammurciano/python-constyle
  summary: A Python library to add style to your console
  description: |
    A Python library to add style to your console.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://abrahammurciano.github.io/python-constyle/constyle
  dev_url: https://github.com/abrahammurciano/python-constyle

extra:
  recipe-maintainers:
    - abrahammurciano
